package BaiTap5_1.Bai1;

public class MultipleCatchBlock5 {
    public static void main(String[] args) {
        // code bị lỗi vì dùng Exception đầu tiên thì các catch ở sau đó ko có nghĩa nữa
        /*try {
            int a[] = new int[5];
            a[5] =30/0;
        }catch (Exception e) {
            System.out.println("Exception");
        }catch (ArithmeticException e) {
            System.out.println("ArithmeticException");
        }catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("ArrayIndexOutOfBoundsException");
        }
        System.out.println("rest of the code...");*/
    }
}
